[project]
name = "toastmasters-report-scrape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playwright",
    "openpyxl",
    "python-dotenv",
    "urllib3",
    "requests",
    "reportlab",
    "pandas"
]
